# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publicar pacote NuGet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Testar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Testar
      run: dotnet test ./DevToolz.Library.Test/DevToolz.Library.Test.csproj --verbosity normal

  Publicar:
    runs-on: windows-latest
    needs: Testar

    steps:
    - name: Verificar API Key
      env:
        SUPER_SECRET: ${{ secrets.NUGET_KEY }}
      run: |
        echo "$SUPER_SECRET"

    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Compilar projeto
      run: dotnet build ./DevToolz.Library/DevToolz.Library.csproj -c Release

    - name: Empacotar
      run: dotnet pack ./DevToolz.Library/DevToolz.Library.csproj -c Release -o ./output

    - name: Enviar para Nuget.org
      env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
      run: dotnet nuget push "./output/*.nupkg" -k ${NUGET_KEY} -s https://api.nuget.org/v3/index.json
