# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publicar pacote NuGet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Testar
      run: dotnet test ./DevToolz.Library.Test/DevToolz.Library.Test.csproj --verbosity normal

  publish:
    runs-on: windows-latest
    needs: test

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Empacotar
      run: dotnet pack ./DevToolz.Library/DevToolz.Library.csproj -c Release -o ./output

    - name: Enviar para Nuget.org
      run: dotnet nuget push ./output/*.nupkg -k $NUGET_KEY -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols --no-dependencies --no-restore
