# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Resturar dependências
      run: dotnet restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  build:
    runs-on: windows-latest
    needs: test

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
        
    - name: Resturar dependências
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
